[package]
name = "rs_hmac"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hash_ctx = { path = "../../hash_ctx" }
internal_hasher = { path = "../../internal_hasher" }

[dev-dependencies]
rs_sha1 = { path = "../rs_sha1" }
