[package]
name = "n_bit_words"
description = "Just a generic wrapper over primitive unsigned integers designed for hashing calculations"
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.0"

[lib]
name = "n_bit_words_lib"
