[package]
name = "rs_hasher_ctx"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "rs_hasher_ctx_lib"

[dependencies]
internal_hasher = { git = "https://github.com/Azgrom/RustySSL.git/" }
internal_state = { git = "https://github.com/Azgrom/RustySSL.git/" }
n_bit_words = { git = "https://github.com/Azgrom/RustySSL.git/" }
