[package]
name = "internal_hasher"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
internal_state = { path = "../internal_state" }
n_bit_words = { path = "../n_bit_words" }
