[package]
authors = ["Rafael Lúcio <rafaellucio@pm.me>"]
description = "a Secure Hash Algorithm library based on git's implementation of SHA, but refactored to make it easier to port, maintain, expand and use"
categories = ["data-structures", "development-tools"]
edition = "2021"
keywords = ["sha", "sha_1", "sha-1"]
license = "GPL-2.0-only"
name = "rusty_sha"
readme = "README.md"
rust-version = "1.66.0"
version = "0.1.0"

[lib]
name = "lib"
path = "src/lib/mod.rs"

#[[bin]]
#name = "main"
#path = "src/bin/mod"

[dependencies]

[dev-dependencies]
criterion = "0.4.0"
openssl = "0.10.44"
openssl-sys = "0.9.79"
sha1 = "0.10.5"
hex-literal = "0.3.4"
hex = "0.4.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "dev"
opt-level = 3
lto = true
codegen-units = 1
strip = false

[[bench]]
name = "benches"
harness = false
