[package]
name = "rs_ssl"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[workspace]
members = [
    "wks/hash_ctx",
    "wks/n_bit_words",
    "wks/internal_state",
    "wks/internal_hasher",
    "wks/hash_functions/*"
]

[workspace.package]
edition = "2021"
license = "GPL-2.0-only"
readme = "README.md"

[[bin]]
name = "main"
path = "src/bin/mod.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "release"

[profile.ci]
inherits = "release"
strip = false
debug = false

[dependencies]
rs_hmac = { path = "wks/hash_functions/rs_hmac" }
rs_keccak_nbits = { path = "wks/hash_functions/rs_keccak_nbits" }
rs_sha1 = { path = "wks/hash_functions/rs_sha1" }
rs_sha224 = { path = "wks/hash_functions/rs_sha224" }
rs_sha256 = { path = "wks/hash_functions/rs_sha256" }
rs_sha384 = { path = "wks/hash_functions/rs_sha384" }
rs_sha512 = { path = "wks/hash_functions/rs_sha512" }
rs_sha512_224 = { path = "wks/hash_functions/rs_sha512_224" }
rs_sha512_256 = { path = "wks/hash_functions/rs_sha512_256" }
rs_shake128 = { path = "wks/hash_functions/rs_shake128" }
rs_sha3_224 = { path = "wks/hash_functions/rs_sha3_224" }
rs_sha3_256 = { path = "wks/hash_functions/rs_sha3_256" }
hash_ctx = { path = "wks/hash_ctx" }

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.4.0"
