[package]
name = "rs_ssl"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[workspace]
members = ["wks/*"]

[workspace.package]
edition = "2021"
license = "GPL-2.0-only"
readme = "README.md"

[[bin]]
name = "main"
path = "src/bin/mod.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
inherits = "release"
strip = false

[profile.ci]
inherits = "release"
strip = false
debug = false

[dependencies]
rs_sha1 = { path = "wks/rs_sha1" }
rs_sha256 = { path = "wks/rs_sha256" }

criterion = { version = "0.4.0", optional = true }
criterion-table = { version = "0.4.2", optional = true }
openssl = { version = "0.10.45", optional = true }
hashes_sha1 = { version = "0.10.5", package = "sha1", optional = true }
sha1_smol = { version = "1.0.0", optional = true }
const-sha1 = { version = "0.2.0", optional = true }

[features]
criterion = ["dep:criterion"]
comparator_build = ["dep:criterion",
    "dep:criterion-table",
    "dep:openssl",
    "dep:hashes_sha1",
    "dep:sha1_smol",
    "dep:const-sha1"]

[[bench]]
name = "benches"
harness = false
