[package]
authors = ["Rafael Lúcio <rafaellucio@pm.me>"]
description = "A Secure Hash Algorithm library based on git's implementation of SHA, but refactored to make it easier to port, maintain, expand and use"
categories = ["data-structures", "development-tools"]
edition = "2021"
keywords = ["sha", "sha_1", "sha-1"]
license = "GPL-2.0-only"
name = "rusty_sha"
readme = "README.md"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
