[package]
authors = ["Rafael Lúcio <rafaellucio@pm.me>"]
description = "A git and openssl based implementation SHA-1 library , but faster, easier to port, maintain, expand and use"
categories = ["data-structures", "development-tools"]
keywords = ["sha", "sha_1", "sha-1"]
name = "rs_sha1"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
n_bit_words = { path = "../../n_bit_words" }
internal_state = { path = "../../internal_state" }
hash_ctx = { path = "../../hash_ctx" }
