[package]
name = "rs_gost_r34_11_94"
description = "GOST R 34.11-94"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
