[package]
authors = ["Rafael Lúcio <rafaellucio@pm.me>"]
keywords = ["sha", "sha_2", "sha_256"]
name = "rs_sha256"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
hash_ctx = { path = "../../hash_ctx" }
internal_state = { path = "../../internal_state" }
n_bit_words = { path = "../../n_bit_words" }
