[package]
authors = ["Rafael Lúcio <rafaellucio@pm.me>"]
keywords = ["sha", "sha_2", "sha_256"]
name = "rs_sha256"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
# Custom name definition because of multiple rmeta candidates error E0465
name = "rs_sha256_lib"
path = "src/lib.rs"

[dependencies]
u32_word = { path = "../../u32_word" }
hash_ctx = { path = "../../hash_ctx" }
