[package]
name = "rs_aes"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bench]]
name = "benches"
harness = false

[dependencies]
hash_ctx = { path = "../../hash_ctx" }
internal_hasher = { path = "../../internal_hasher" }
internal_state = { path = "../../internal_state" }
n_bit_words = { path = "../../n_bit_words" }

[dev-dependencies]
criterion = "0.4.0"
