[package]
name = "rs_cast_128"
description = "A cast-128 implementation in Rust"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
