[package]
name = "rs_diffie_hellman"
description = "Diffie-Hellman key exchange implementation in Rust"
version = "0.1.0"
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
