[package]
name = "internal_state"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "internal_state"

[dependencies]
hash_ctx = { path = "../hash_ctx" }
internal_hasher = { path = "../internal_hasher" }
n_bit_words = { path = "../n_bit_words" }
