[package]
name = "internal_state"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "internal_state"

[dependencies]
n_bit_words = { git = "https://github.com/Azgrom/RustySSL.git/", version = "0.1.0" }
